"""BM25IndexBuilder for PostgreSQL tsvector-based document indexing.

This module provides a BM25 indexing implementation that uses PostgreSQL's
native tsvector functionality (Block A-3) for full-text search. The index
builder works in parallel with vector indexing through asyncio.gather.
"""

import json
import logging

import asyncpg

from llm_client.config import Settings

from .models import Document

logger = logging.getLogger(__name__)


class BM25IndexBuilder:
    """Builds BM25 index in PostgreSQL using tsvector, parallel to vector indexing.
    
    This class handles document indexing into the `documents` table where the
    `search_vector` column is auto-generated by PostgreSQL via 
    GENERATED ALWAYS AS STORED (migration 007).
    
    Key features:
    - Idempotent indexing (ON CONFLICT upsert)
    - Batch indexing for bulk loads
    - Parallel execution with vector indexing via asyncio.gather
    - Text search configuration from environment
    """
    
    def __init__(
        self, 
        pg_pool: asyncpg.Pool, 
        text_search_config: str = "english"
    ):
        """Initialize BM25IndexBuilder.
        
        Args:
            pg_pool: asyncpg connection pool for PostgreSQL
            text_search_config: PostgreSQL text search configuration 
                (e.g., "english", "russian")
        """
        self._pool = pg_pool
        self._text_search_config = text_search_config
        
    async def index_document(self, document: Document) -> None:
        """Insert or update a document in the documents table.
        
        Uses ON CONFLICT (content_hash) DO UPDATE for idempotency. The
        search_vector is automatically computed by PostgreSQL via 
        GENERATED ALWAYS AS STORED.
        
        Args:
            document: Document to index
            
        Raises:
            asyncpg.PostgresError: If database operation fails
        """
        async with self._pool.acquire() as conn:
            # Set text search config for this connection
            await conn.execute(f"SET pg_text_search_config = '{self._text_search_config}'")
            
            await conn.execute(
                """
                INSERT INTO documents (
                    id, user_id, source_type, source_uri, 
                    content_hash, content, metadata
                )
                VALUES ($1, $2, $3, $4, $5, $6, $7)
                ON CONFLICT (content_hash) DO UPDATE SET
                    content = EXCLUDED.content,
                    metadata = EXCLUDED.metadata,
                    source_uri = EXCLUDED.source_uri
                """,
                document.id,
                document.user_id,
                document.source_type,
                document.source_uri,
                document.content_hash,
                document.content,
                json.dumps(document.metadata) if document.metadata else '{}'
            )
            
        logger.debug("Indexed document %s", document.id)
    
    async def index_documents_batch(self, documents: list[Document]) -> None:
        """Batch insert multiple documents for bulk indexing.
        
        More efficient than calling index_document multiple times for
        large document collections (e.g., initial load of 10k documents).
        
        Args:
            documents: List of documents to index
            
        Raises:
            asyncpg.PostgresError: If database operation fails
        """
        if not documents:
            return
            
        # Prepare data for executemany
        document_data = [
            (
                doc.id, doc.user_id, doc.source_type, doc.source_uri,
                doc.content_hash, doc.content, 
                json.dumps(doc.metadata) if doc.metadata else '{}'
            )
            for doc in documents
        ]
        
        async with self._pool.acquire() as conn:
            # Set text search config for this connection
            await conn.execute(f"SET pg_text_search_config = '{self._text_search_config}'")
            
            await conn.executemany(
                """
                INSERT INTO documents (
                    id, user_id, source_type, source_uri, 
                    content_hash, content, metadata
                )
                VALUES ($1, $2, $3, $4, $5, $6, $7)
                ON CONFLICT (content_hash) DO UPDATE SET
                    content = EXCLUDED.content,
                    metadata = EXCLUDED.metadata,
                    source_uri = EXCLUDED.source_uri
                """,
                document_data
            )
            
        logger.info("Batch indexed %d documents", len(documents))
    
    async def delete_document(self, document_id: str) -> None:
        """Delete a document from the documents table.
        
        The tsvector column is automatically deleted via CASCADE.
        
        Args:
            document_id: ID of document to delete
            
        Raises:
            asyncpg.PostgresError: If database operation fails
        """
        async with self._pool.acquire() as conn:
            result = await conn.execute(
                "DELETE FROM documents WHERE id = $1",
                document_id
            )
            
        # Check if document was actually deleted
        if "DELETE 0" in result:
            logger.warning("Document %s not found for deletion", document_id)
        else:
            logger.debug("Deleted document %s", document_id)
    
    @classmethod
    async def create_from_settings(cls, settings: Settings) -> "BM25IndexBuilder":
        """Create BM25IndexBuilder from application settings.
        
        Args:
            settings: Application settings with database configuration
            
        Returns:
            BM25IndexBuilder instance
        """
        pg_url = settings.database_url.replace("postgresql+asyncpg://", "postgresql://")
        pool = asyncpg.create_pool(
            pg_url,
            min_size=1,
            max_size=5,
            command_timeout=60,
        )
        return cls(
            pg_pool=await pool,
            text_search_config=getattr(settings, "pg_text_search_config", "english")
        )