"""BM25IndexBuilder for PostgreSQL tsvector-based document indexing.

This module provides a BM25 indexing implementation that uses PostgreSQL's
native tsvector functionality (Block A-3) for full-text search. The index
builder works in parallel with vector indexing through asyncio.gather.
"""

import hashlib
import json
import logging
from collections import defaultdict

import asyncpg

from llm_client.config import Settings

from .models import Chunk, Document

logger = logging.getLogger(__name__)


class BM25IndexBuilder:
    """Builds BM25 index in PostgreSQL using tsvector, parallel to vector indexing.

    This class handles document indexing into the `documents` table where the
    `search_vector` column is auto-generated by PostgreSQL via
    GENERATED ALWAYS AS STORED (migration 007/008).

    Key features:
    - Idempotent indexing (ON CONFLICT upsert on content_hash)
    - Batch indexing for bulk loads
    - Parallel execution with vector indexing via asyncio.gather
    - Text search configuration from environment
    """

    def __init__(
        self,
        pg_pool: asyncpg.Pool,
        text_search_config: str = "english",
    ):
        """Initialize BM25IndexBuilder.

        Args:
            pg_pool: asyncpg connection pool for PostgreSQL
            text_search_config: PostgreSQL text search configuration
                (e.g., "english", "russian")
        """
        self._pool = pg_pool
        self._text_search_config = text_search_config

    @property
    def pg_pool(self) -> asyncpg.Pool:
        return self._pool

    async def index_document(self, document: Document) -> None:
        """Insert or update a document in the documents table.

        Uses ON CONFLICT (content_hash) DO UPDATE for idempotency. The
        search_vector is automatically computed by PostgreSQL via
        GENERATED ALWAYS AS STORED — the INSERT never supplies it.

        Args:
            document: Document to index

        Raises:
            asyncpg.PostgresError: If database operation fails
        """
        async with self._pool.acquire() as conn:
            await conn.execute(
                """
                INSERT INTO documents (
                    id, user_id, source_type, source_uri,
                    content_hash, content, metadata
                )
                VALUES ($1, $2, $3, $4, $5, $6, $7)
                ON CONFLICT (content_hash) DO UPDATE SET
                    content = EXCLUDED.content,
                    metadata = EXCLUDED.metadata,
                    source_uri = EXCLUDED.source_uri
                """,
                document.id,
                document.user_id,
                document.source_type,
                document.source_uri,
                document.content_hash,
                document.content,
                json.dumps(document.metadata) if document.metadata else "{}",
            )

        logger.debug("Indexed document %s", document.id)

    async def index_documents_batch(self, documents: list[Document]) -> None:
        """Batch insert multiple documents for bulk indexing.

        More efficient than calling index_document multiple times for
        large document collections (e.g., initial load of 10k documents).

        Args:
            documents: List of documents to index

        Raises:
            asyncpg.PostgresError: If database operation fails
        """
        if not documents:
            return

        document_data = [
            (
                doc.id,
                doc.user_id,
                doc.source_type,
                doc.source_uri,
                doc.content_hash,
                doc.content,
                json.dumps(doc.metadata) if doc.metadata else "{}",
            )
            for doc in documents
        ]

        async with self._pool.acquire() as conn:
            await conn.executemany(
                """
                INSERT INTO documents (
                    id, user_id, source_type, source_uri,
                    content_hash, content, metadata
                )
                VALUES ($1, $2, $3, $4, $5, $6, $7)
                ON CONFLICT (content_hash) DO UPDATE SET
                    content = EXCLUDED.content,
                    metadata = EXCLUDED.metadata,
                    source_uri = EXCLUDED.source_uri
                    """,
                document_data,
            )

        logger.info("Batch indexed %d documents", len(documents))

    async def index_chunks(self, chunks: list[Chunk]) -> None:
        """Index chunked documents by concatenating chunks into parent content.

        Chunks sharing a document_id are sorted by chunk_index and joined
        with newlines, then upserted as a single documents row. Per D-2
        anti-pattern guidance, chunks are NOT stored in a separate table —
        BM25 and vector retrieval operate on the same document granularity.
        """
        if not chunks:
            return

        by_doc: dict[str, list[Chunk]] = defaultdict(list)
        for chunk in chunks:
            by_doc[chunk.document_id].append(chunk)

        documents: list[Document] = []
        for doc_id, doc_chunks in by_doc.items():
            ordered = sorted(doc_chunks, key=lambda c: c.chunk_index)
            content = "\n".join(c.content for c in ordered)
            first = ordered[0]
            documents.append(
                Document(
                    id=doc_id,
                    user_id=first.user_id,
                    source_type=first.source_type,
                    source_uri=first.source_uri,
                    content_hash=first.content_hash
                    or hashlib.sha256(content.encode("utf-8")).hexdigest(),
                    content=content,
                    metadata=first.metadata,
                )
            )

        await self.index_documents_batch(documents)
        logger.info("Indexed %d documents from %d chunks", len(documents), len(chunks))

    async def delete_document(self, document_id: str) -> None:
        """Delete a document from the documents table.

        The tsvector column is deleted with the row (generated column).

        Args:
            document_id: ID of document to delete

        Raises:
            asyncpg.PostgresError: If database operation fails
        """
        async with self._pool.acquire() as conn:
            result = await conn.execute(
                "DELETE FROM documents WHERE id = $1",
                document_id,
            )

        if "DELETE 0" in result:
            logger.warning("Document %s not found for deletion", document_id)
        else:
            logger.debug("Deleted document %s", document_id)

    @classmethod
    async def create_from_settings(
        cls,
        settings: Settings,
        pg_pool: asyncpg.Pool | None = None,
    ) -> "BM25IndexBuilder":
        """Create BM25IndexBuilder from application settings.

        When ``pg_pool`` is provided the caller owns its lifecycle — no new
        pool is created and none is closed here. Without a pool a private
        pool is created; the caller must close ``builder.pg_pool`` when done.
        """
        if pg_pool is None:
            pg_url = settings.database_url.replace(
                "postgresql+asyncpg://", "postgresql://"
            )
            pg_pool = await asyncpg.create_pool(
                pg_url,
                min_size=1,
                max_size=5,
                command_timeout=60,
            )
        return cls(
            pg_pool=pg_pool,
            text_search_config=settings.pg_text_search_config,
        )
